XRPLF/clio

CMakeLists.txt
handlers/AccountChannels.cpp
handlers/AccountCurrencies.cpp
handlers/AccountLines.cpp
handlers/AccountObjects.cpp
handlers/AccountOffers.cpp
handlers/BookOffers.cpp
handlers/RPCHelpers.cpp
handlers/RPCHelpers.h
websocket_server_async.cpp

Adds handlers for Account RPCs
`account_lines` `account_channels`, `account_objects`, `account_currencies`, `account_offers`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cjcobb23/xrpl-reporting/1)

Accounts RPC Handler

---

handlers/RPCHelpers.cpp
handlers/Subscribe.cpp
reporting/ReportingETL.cpp
reporting/server/session.cpp
reporting/server/session.h

Adds support for subscriptions to `ledger` and `transactions` streams as well as `account` subscriptions.
fixes #7 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cjcobb23/xrpl-reporting/2)

Subscribe/Unsubscribe RPC handlers

---

CMakeLists.txt
handlers/ChannelAuthorize.cpp
handlers/ChannelVerify.cpp
handlers/RPCHelpers.cpp
handlers/RPCHelpers.h
reporting/CassandraBackend.cpp
websocket_server_async.cpp

I borked the rebase, and so git deleted my old PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cjcobb23/xrpl-reporting/19)

impliments paychannel verify/authorize

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cjcobb23/clio/60)

Install cmake, `mkdir`

---

src/rpc/handlers/ServerInfo.cpp

For native rippled compatibility
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cjcobb23/clio/61)

Remove ledger range spaces (server_info, complete_ledgers)

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cjcobb23/clio/63)

protobuf v2 is required.

---

src/etl/ETLSource.cpp
src/etl/ETLSource.h
src/etl/ReportingETL.cpp
src/etl/ReportingETL.h

Parallelizes the initial database download in the same manner as reporting mode.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cjcobb23/clio/54)

parallelizes download

---

src/rpc/RPC.cpp
src/webserver/HttpBase.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cjcobb23/clio/65)

Handle case where params is null

---

src/backend/CassandraBackend.cpp
src/rpc/handlers/AccountTx.cpp

Removes the `index` partition key from the `account_tx` table. 
This greatly simplifies `fetchAccountTransactions` for `CassandraBackend`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cjcobb23/clio/70)

refactor account_tx

---

.gitignore
CMakeLists.txt

This at least prevents rebuilding everything all the time but something still seems wrong.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cjcobb23/clio/73)

Stop rebuilding everything everytime

---

CMakeLists.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cjcobb23/clio/87)

build tests optionally

---

README.md
src/backend/CassandraBackend.cpp

This PR adds some simple changes to the build instructions in the README.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cjcobb23/clio/91)

Advance readme

---

src/webserver/WsBase.h

Capture ws session as a shared ptr in handler.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cjcobb23/clio/99)

capture websocket session as shared_ptr

---

CMake/settings.cmake
CMakeLists.txt
src/backend/BackendInterface.cpp
src/backend/CassandraBackend.cpp
src/backend/Pg.cpp
src/backend/PostgresBackend.cpp
src/etl/ETLSource.cpp
src/etl/ETLSource.h
src/etl/ReportingETL.cpp
src/rpc/RPC.h
src/rpc/handlers/AccountInfo.cpp
src/rpc/handlers/LedgerData.cpp
src/rpc/handlers/LedgerEntry.cpp
src/webserver/DOSGuard.h
src/webserver/PlainWsSession.h
src/webserver/SslWsSession.h
src/webserver/WsBase.h
unittests/main.cpp

This small change does some minor refactoring and adds C++20 features.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cjcobb23/clio/96)

Advance DOSGuard

---

CMake/deps/Postgres.cmake

Whoops, rippled has the same issue.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cjcobb23/clio/93)

Link postgres statically

---

src/webserver/DOSGuard.h

Don't fail when the config is malformed
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cjcobb23/clio/103)

Make DOSGuard config loading more resilient

---

README.md
src/backend/README.md
unittests/README.md
unittests/main.cpp

Added README documentation for unit tests detailing how to run it and how to maintain it. 
Also fixed some other minor typos in other documentations.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cjcobb23/clio/106)

Added README documentation for unit tests and fixed typos

---

src/backend/BackendInterface.cpp
src/backend/BackendInterface.h
src/backend/CassandraBackend.h
src/backend/Pg.cpp
src/etl/ReportingETL.cpp
src/subscriptions/SubscriptionManager.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cjcobb23/clio/108)

Assorted valgrind fixes

---

src/etl/ETLSource.cpp
src/rpc/Counters.cpp
src/rpc/RPC.cpp
src/rpc/RPC.h
src/rpc/RPCHelpers.cpp
src/rpc/RPCHelpers.h
src/rpc/handlers/AccountChannels.cpp
src/rpc/handlers/AccountCurrencies.cpp
src/rpc/handlers/AccountLines.cpp
src/rpc/handlers/AccountObjects.cpp
src/rpc/handlers/AccountOffers.cpp
src/rpc/handlers/AccountTx.cpp
src/rpc/handlers/GatewayBalances.cpp
src/rpc/handlers/NoRippleCheck.cpp
src/webserver/HttpBase.h
src/webserver/WsBase.h
test.py

* Websocket should be able to use `command` or `method
* when `ledger_index` is string, try to parse as a number
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cjcobb23/clio/110)

Issues found by AB testing

---

src/backend/BackendFactory.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cjcobb23/clio/120)

Develop to master

---

RELEASENOTES.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cjcobb23/clio/122)

add RELEASENOTES.md
